'use client';
import { useEffect, useRef, useState } from 'react';
import { frameTarget, easeFrame } from './scrub';
import { compressPhoto } from './photos';
import {Logo,Music,PhotoViewer} from './media';
import { flushSync } from 'react-dom';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, Plus, MoveHorizontal, Menu, X, Upload, Trash2, ImageIcon, Check, Pencil, Heart, MessageCircle, Send } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { deleteGuestbookComment, deleteGuestbookMessage, deletePhoto, likeGuestbookMessage, listAlbumCovers, listGuestbook, listGuestbookComments, listPhotos, postGuestbookComment, postGuestbookMessage, PUBLIC_ALBUM, rankGuestbookMessages, renameAlbum, saveAlbumCover, updateGuestbookMessage, uploadPhotos, type GuestbookComment, type GuestbookMessage } from './supabase';

type Photo = { src: string; name: string; note: string; file?: File; path?: string; album?: string };
const asset=(path:string)=>new URL(path,document.baseURI).href;
const samples: Photo[] = [{src:asset('village-group.png'),name:'童话村 · 冒险家大合影',note:PUBLIC_ALBUM,album:PUBLIC_ALBUM}];
const ALL_ALBUMS='全部照片';
const sponsors = [ ['梦之终结','1550W'],['飞琼','1000W'],['快乐剑客 007','500W'],['圣诞丶 1230','500W'],['Yyttoo','500W'],['擂辣椒皮蛋','500W'],['纠结丶','500W'],['过不去丶','500W'],['廿年之前','500W'],['闪亮晨星','500W'],['喜洋洋睡不醒','500W'],['汤二蛋','500W'],['神奇小豆来啦','500W'],['希喵','500W'],['疯狂牛市','500W'],['波吉','88.8RMB'],['茶尔思','88.88RMB'],['炫彩任又欠','88.88RMB'],['FS 丶劫','88.88RMB'],['月落弯','88.88RMB'] ];
const events=[['08.13','童话村建村','我们的故事，从这一天开始。'],['08.20','第一次进村大会','自由市场58线1洞'],['08.26','第二次进村大会','自由市场58线17洞']];
const honors=[
 {name:'小蓝天丶',job:'勇士',date:'2026.09.10',image:'honor-xiaolantian.png'},
 {name:'华福证券李鑫',job:'龙骑士',date:'2026.09.13',image:'honor-huafu.png'},
];
const messageTime=(value:string)=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
const BunnyMascot=()=> <span className="album-mascot bunny-mascot" title="小兔Daily" aria-label="会动的小兔子标识"><svg viewBox="0 0 64 64" aria-hidden="true"><g className="bunny-ear bunny-ear-left"><ellipse cx="23" cy="17" rx="8" ry="16" fill="#fff8ee" stroke="#9c695f" strokeWidth="2"/><ellipse cx="23" cy="17" rx="3.2" ry="10" fill="#f5aaa9"/></g><g className="bunny-ear bunny-ear-right"><ellipse cx="43" cy="17" rx="8" ry="16" fill="#fff8ee" stroke="#9c695f" strokeWidth="2"/><ellipse cx="43" cy="17" rx="3.2" ry="10" fill="#f5aaa9"/></g><path d="M13 43c0-14 8-22 19-22s20 8 20 22c0 11-8 17-20 17S13 54 13 43Z" fill="#fff8ee" stroke="#9c695f" strokeWidth="2"/><ellipse className="mascot-eye" cx="25" cy="42" rx="2.2" ry="3" fill="#473636"/><ellipse className="mascot-eye" cx="41" cy="42" rx="2.2" ry="3" fill="#473636"/><circle cx="20" cy="48" r="3" fill="#f6a5aa" opacity=".72"/><circle cx="46" cy="48" r="3" fill="#f6a5aa" opacity=".72"/><path d="M30 47q2 2 4 0m-2-1v4" fill="none" stroke="#7e4c50" strokeWidth="1.8" strokeLinecap="round"/></svg></span>;
const LycheeMascot=()=> <span className="album-mascot lychee-mascot" title="小青蛙的旅行日记" aria-label="会动的荔枝和小鱼标识"><svg viewBox="0 0 94 64" aria-hidden="true"><g className="lychee-leaves"><path d="M31 17C20 5 12 7 8 13c8 4 15 5 23 4Z" fill="#6ba74b" stroke="#386733" strokeWidth="2"/><path d="M34 16C42 3 54 6 57 12c-7 5-14 7-23 4Z" fill="#83b957" stroke="#386733" strokeWidth="2"/><path d="M31 20c2-8 4-11 8-15" fill="none" stroke="#654735" strokeWidth="3" strokeLinecap="round"/></g><circle cx="32" cy="38" r="20" fill="#eb6374" stroke="#9f3548" strokeWidth="2"/><g fill="none" stroke="#c7465b" strokeWidth="1.5" strokeLinecap="round"><path d="m18 28 3-1m-4 8 3 1m1 9-2 2m10-24 1 3m10-1-2 3m9 5-3 1m2 9-3-1m-4 10-1-3m-10 4 1-3"/></g><ellipse className="mascot-eye" cx="25" cy="38" rx="2.2" ry="2.8" fill="#4b3033"/><ellipse className="mascot-eye" cx="39" cy="38" rx="2.2" ry="2.8" fill="#4b3033"/><circle cx="21" cy="44" r="2.6" fill="#f99aa2"/><circle cx="43" cy="44" r="2.6" fill="#f99aa2"/><path d="M29 44q3 3 6 0" fill="none" stroke="#72343e" strokeWidth="1.8" strokeLinecap="round"/><g className="little-fish"><path className="fish-tail" d="m78 35 13-9v18Z" fill="#f2a64b" stroke="#8e5d3d" strokeWidth="2" strokeLinejoin="round"/><path d="M78 22c-14 0-24 7-24 13s10 13 24 13c6-6 6-20 0-26Z" fill="#70c5cf" stroke="#376c76" strokeWidth="2"/><path d="m66 23 6-7 5 8" fill="#8bd5d7" stroke="#376c76" strokeWidth="2" strokeLinejoin="round"/><circle cx="62" cy="32" r="2" fill="#354b4d"/><path d="M57 39q5 3 9 0" fill="none" stroke="#376c76" strokeWidth="1.7" strokeLinecap="round"/><circle cx="60" cy="37" r="2.2" fill="#f39ca0" opacity=".75"/></g></svg></span>;
const BoatMascot=()=> <span className="album-mascot boat-mascot" title="小船长个人秀" aria-label="会动的小轮船标识"><svg viewBox="0 0 64 64" aria-hidden="true"><g className="boat-sail"><path d="M31 8v30" stroke="#6d4937" strokeWidth="3" strokeLinecap="round"/><path d="M29 11 13 34h16Z" fill="#fff5df" stroke="#a96a58" strokeWidth="2"/><path d="m33 16 15 18H33Z" fill="#e87368" stroke="#a94f4c" strokeWidth="2"/><path d="M31 8c5 0 8 2 10 4-3 2-6 2-10 1Z" fill="#f0b44f"/></g><path d="M8 37h48l-7 15c-2 4-6 6-11 6H24c-5 0-8-2-10-6Z" fill="#6db5c4" stroke="#315f6d" strokeWidth="2" strokeLinejoin="round"/><path d="M15 44h34" stroke="#fff3d7" strokeWidth="3" strokeLinecap="round"/><circle cx="25" cy="49" r="2.3" fill="#fff3d7"/><circle cx="39" cy="49" r="2.3" fill="#fff3d7"/><path className="boat-wave" d="M7 59c5-3 9-3 14 0s9 3 14 0 9-3 14 0 8 3 11 1" fill="none" stroke="#82cbd5" strokeWidth="2.5" strokeLinecap="round"/></svg></span>;
const SheepMascot=()=> <span className="album-mascot sheep-mascot" title="喜羊羊的征婚相册" aria-label="会动的喜羊羊标识"><svg viewBox="0 0 64 64" aria-hidden="true"><g className="sheep-ears"><path d="M17 30C7 25 7 36 18 38Z" fill="#f2b8a0" stroke="#875e51" strokeWidth="2"/><path d="M47 30c10-5 10 6-1 8Z" fill="#f2b8a0" stroke="#875e51" strokeWidth="2"/></g><g fill="none" stroke="#a47747" strokeWidth="4" strokeLinecap="round"><path d="M19 26c-10-1-11-12-4-15 7-3 12 5 7 10"/><path d="M45 26c10-1 11-12 4-15-7-3-12 5-7 10"/></g><path d="M16 29c-5-4-3-11 3-12-1-6 7-9 11-5 4-5 12-2 12 4 7-1 10 7 5 12 5 8 3 27-15 30C14 55 12 38 16 29Z" fill="#fff9e9" stroke="#816c59" strokeWidth="2"/><path d="M22 31c1-8 19-8 20 0v13c0 8-5 12-10 12s-10-4-10-12Z" fill="#f3c1a8"/><ellipse className="mascot-eye" cx="27" cy="38" rx="2.2" ry="3" fill="#3f3835"/><ellipse className="mascot-eye" cx="37" cy="38" rx="2.2" ry="3" fill="#3f3835"/><circle cx="24" cy="44" r="2.5" fill="#ee9197" opacity=".7"/><circle cx="40" cy="44" r="2.5" fill="#ee9197" opacity=".7"/><path d="M29 45q3 3 6 0" fill="none" stroke="#7c5149" strokeWidth="1.7" strokeLinecap="round"/><path d="M19 52q13 8 26 0" fill="none" stroke="#4f9ccc" strokeWidth="5" strokeLinecap="round"/><circle className="sheep-bell" cx="32" cy="57" r="4" fill="#f2bd43" stroke="#8d672a" strokeWidth="1.5"/></svg></span>;
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null);
 const [framesReady,setFramesReady]=useState(false);
 const [menu,setMenu]=useState(false);
 const [upload,setUpload]=useState(false);
 const [photos,setPhotos]=useState<Photo[]>(samples);
 const [covers,setCovers]=useState<Record<string,string>>({});
 const [activeAlbum,setActiveAlbum]=useState(ALL_ALBUMS);const [albumName,setAlbumName]=useState(PUBLIC_ALBUM);
 const [coverAlbum,setCoverAlbum]=useState<string|null>(null);const [coverPhoto,setCoverPhoto]=useState<Photo|null>(null);const [coverFile,setCoverFile]=useState<File|null>(null);const [coverPreview,setCoverPreview]=useState('');const [coverKey,setCoverKey]=useState('');const [coverSaving,setCoverSaving]=useState(false);const [coverError,setCoverError]=useState('');
 const [renameTarget,setRenameTarget]=useState<string|null>(null);const [newAlbumName,setNewAlbumName]=useState('');const [renameKey,setRenameKey]=useState('');const [renaming,setRenaming]=useState(false);const [renameError,setRenameError]=useState('');
 const [messages,setMessages]=useState<GuestbookMessage[]>([]);const [messageName,setMessageName]=useState('');const [messageText,setMessageText]=useState('');const [messagePosted,setMessagePosted]=useState(false);const [messageLoading,setMessageLoading]=useState(true);const [messageSaving,setMessageSaving]=useState(false);const [messageError,setMessageError]=useState('');
 const [manageMessage,setManageMessage]=useState<GuestbookMessage|null>(null);const [manageName,setManageName]=useState('');const [manageText,setManageText]=useState('');const [manageKey,setManageKey]=useState('');const [manageSaving,setManageSaving]=useState(false);const [manageError,setManageError]=useState('');const [deleteArmed,setDeleteArmed]=useState(false);
 const [commentMessage,setCommentMessage]=useState<GuestbookMessage|null>(null);const [comments,setComments]=useState<GuestbookComment[]>([]);const [commentName,setCommentName]=useState('');const [commentText,setCommentText]=useState('');const [commentLoading,setCommentLoading]=useState(false);const [commentSaving,setCommentSaving]=useState(false);const [commentPosted,setCommentPosted]=useState(false);const [commentError,setCommentError]=useState('');
 const [deleteComment,setDeleteComment]=useState<GuestbookComment|null>(null);const [commentDeleteKey,setCommentDeleteKey]=useState('');const [commentDeleting,setCommentDeleting]=useState(false);const [commentDeleteError,setCommentDeleteError]=useState('');
 const [active,setActive]=useState<number|null>(null);
 const [deleteTarget,setDeleteTarget]=useState<Photo|null>(null);const [deleteKey,setDeleteKey]=useState('');const [deleting,setDeleting]=useState(false);const [deleteError,setDeleteError]=useState('');
 const [pending,setPending]=useState<Photo[]>([]);
 const [error,setError]=useState('');
 const [uploadKey,setUploadKey]=useState('');const [saving,setSaving]=useState(false);const [compressing,setCompressing]=useState(false);const [albumError,setAlbumError]=useState('');
 const urls=useRef<string[]>([]);
 useEffect(()=>{document.documentElement.classList.add('reveal-ready');const nodes=[...document.querySelectorAll<HTMLElement>('#guestbook,#album,#events,#honors,#sponsors')];nodes.forEach(node=>node.classList.add('reveal-section'));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -8%'});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);
 useEffect(()=>()=>urls.current.forEach(URL.revokeObjectURL),[]);
 useEffect(()=>{let stopped=false;Promise.all([listPhotos(),listAlbumCovers()]).then(([all,albumCovers])=>{if(!stopped){setPhotos(all);setCovers(albumCovers)}}).catch(()=>{if(!stopped)setAlbumError('相册暂时未能加载，请刷新重试。')});return()=>{stopped=true}},[]);
 useEffect(()=>{let stopped=false;setMessagePosted(localStorage.getItem('tonghuacun-message-posted')==='1');listGuestbook().then(data=>{if(!stopped)setMessages(rankGuestbookMessages(data))}).catch(()=>{if(!stopped)setMessageError('留言暂时未能加载，请刷新重试。')}).finally(()=>{if(!stopped)setMessageLoading(false)});return()=>{stopped=true}},[]);
 useEffect(()=>{
  const el=canvas.current;const ctx=el?.getContext('2d');if(!el||!ctx)return;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');const touch=matchMedia('(pointer: coarse)');
  let stopped=false,raf=0,target=40,current=40,last=-1,lastTime=0,visible=true;
  const surfaces:HTMLCanvasElement[]=[];
  const load=async(i:number)=>{const img=new Image();img.src=asset(`frames/${String(i).padStart(3,'0')}.webp`);await img.decode();if(stopped)return;const surface=document.createElement('canvas');surface.width=800;surface.height=450;surface.getContext('2d')!.drawImage(img,0,0,800,450);surfaces[i]=surface};
  const draw=(i:number)=>{if(!surfaces[i])return;ctx.clearRect(0,0,800,450);ctx.drawImage(surfaces[i],0,0);last=i};
  const render=(time:number)=>{if(stopped)return;const dt=lastTime?Math.min(time-lastTime,50):16;lastTime=time;
   if(visible&&!document.hidden){if(touch.matches&&!reduced.matches)target=40+40*Math.sin(time/3200);
   current=reduced.matches?40:easeFrame(current,target,dt);const index=Math.round(current);if(index!==last)draw(index)}raf=requestAnimationFrame(render);
  };
  const move=(e:MouseEvent)=>{if(!touch.matches&&!reduced.matches)target=frameTarget(e.clientX,innerWidth)};
  const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting});observer.observe(el);
  (async()=>{await load(40);if(stopped)return;draw(40);setFramesReady(true);
   const todo=Array.from({length:81},(_,i)=>i).filter(i=>i!==40);let next=0;
   await Promise.all(Array.from({length:4},async()=>{while(next<todo.length&&!stopped){await load(todo[next++]);await new Promise(r=>setTimeout(r,0))}}));
   if(stopped)return;raf=requestAnimationFrame(render);window.addEventListener('mousemove',move);
  })().catch(()=>{});
  return()=>{stopped=true;cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('mousemove',move)};
 },[]);
 useEffect(()=>{
 const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(!context)return;const lifecycle=new AbortController();
 try{Promise.resolve(context.registerTool({name:'open_album_photo',description:'Open an existing photo in the album lightbox. Index starts at 1.',inputSchema:{type:'object',properties:{index:{type:'integer',minimum:1}},required:['index'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const i=(input as {index?:unknown})?.index;if(typeof i!=='number'||!Number.isInteger(i)||i<1||i>photos.length)throw new Error('Photo index out of range');flushSync(()=>setActive(i-1));return{opened:i,title:photos[i-1].name}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[photos]);
 const choose=async(files:FileList|null)=>{if(!files||saving||compressing)return;const accepted=Array.from(files).filter(f=>['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)&&f.size<=20*1024*1024);setError(accepted.length<files.length?'部分文件未加入：请选择 20 MB 以内的 JPG、PNG、WebP 或 GIF。':'');setCompressing(true);try{const prepared=await Promise.all(accepted.map(async original=>({file:await compressPhoto(original).catch(()=>original),name:original.name.replace(/\.[^.]+$/,'')})));setPending(p=>[...p,...prepared.map(({file,name})=>{const src=URL.createObjectURL(file);urls.current.push(src);return{src,name,note:'待上传',file}})])}finally{setCompressing(false)}};
 const savePhotos=async()=>{setSaving(true);setError('');try{const targetAlbum=albumName.trim()||PUBLIC_ALBUM;const items=pending.flatMap(p=>p.file?[{file:p.file,title:p.name}]:[]);const added=await uploadPhotos(uploadKey,targetAlbum,items);setPhotos(p=>[...added.reverse(),...p]);setActiveAlbum(targetAlbum);setPending([]);setUploadKey('');setUpload(false);setTimeout(()=>document.getElementById('album')?.scrollIntoView({behavior:'smooth'}),150)}catch(e){setError(e instanceof Error?e.message:'网络异常，请重试')}finally{setSaving(false)}};
 const confirmDelete=async()=>{if(!deleteTarget?.path)return;setDeleting(true);setDeleteError('');try{await deletePhoto(deleteKey,deleteTarget.path);setPhotos(p=>p.filter(item=>item.path!==deleteTarget.path));setDeleteTarget(null);setDeleteKey('')}catch(e){setDeleteError(e instanceof Error?e.message:'删除失败，请重试')}finally{setDeleting(false)}};
 const chooseCoverFile=(file:File|null)=>{if(coverPreview)URL.revokeObjectURL(coverPreview);setCoverError('');setCoverFile(file);setCoverPhoto(null);setCoverPreview(file?URL.createObjectURL(file):'')};
 const closeCover=()=>{if(coverPreview)URL.revokeObjectURL(coverPreview);setCoverAlbum(null);setCoverPhoto(null);setCoverFile(null);setCoverPreview('');setCoverKey('');setCoverError('')};
 const confirmCover=async()=>{if(!coverAlbum||(!coverFile&&!coverPhoto))return;setCoverSaving(true);setCoverError('');try{const source=coverFile?await compressPhoto(coverFile):{src:coverPhoto!.src};const src=await saveAlbumCover(coverKey,coverAlbum,source);setCovers(current=>({...current,[coverAlbum]:src}));closeCover()}catch(e){setCoverError(e instanceof Error?e.message:'封面设置失败，请重试')}finally{setCoverSaving(false)}};
 const closeRename=()=>{setRenameTarget(null);setNewAlbumName('');setRenameKey('');setRenameError('')};
 const confirmRename=async()=>{if(!renameTarget)return;const nextName=newAlbumName.trim();if(albumNames.includes(nextName)){setRenameError('这个相册名称已经存在，请换一个名字。');return}setRenaming(true);setRenameError('');try{const currentPhotos=photos.filter(photo=>(photo.album??PUBLIC_ALBUM)===renameTarget);const moved=await renameAlbum(renameKey,renameTarget,nextName,currentPhotos,covers[renameTarget]);const byOldPath=new Map(moved.map(item=>[item.oldPath,item]));setPhotos(current=>current.map(photo=>{const replacement=photo.path?byOldPath.get(photo.path):undefined;return replacement?{...photo,...replacement,album:nextName,note:nextName}:photo}));setCovers(current=>{const updated={...current};if(updated[renameTarget]){updated[nextName]=updated[renameTarget];delete updated[renameTarget]}return updated});setActiveAlbum(nextName);closeRename()}catch(e){setRenameError(e instanceof Error?e.message:'相册重命名失败，请重试')}finally{setRenaming(false)}};
 const submitMessage=async()=>{setMessageSaving(true);setMessageError('');try{const added=await postGuestbookMessage(messageName,messageText);setMessages(current=>rankGuestbookMessages([added,...current]));setMessagePosted(true);setMessageName('');setMessageText('')}catch(e){const text=e instanceof Error?e.message:'留言失败，请重试';setMessageError(text);if(text.includes('已经留下过'))setMessagePosted(true)}finally{setMessageSaving(false)}};
 const likeMessage=async(id:number)=>{setMessageError('');try{await likeGuestbookMessage(id);setMessages(current=>rankGuestbookMessages(current.map(message=>message.id===id?{...message,likes:message.likes+1,liked:true}:message)))}catch(e){const text=e instanceof Error?e.message:'点赞失败，请重试';setMessageError(text);if(text.includes('已经给这条'))setMessages(current=>current.map(message=>message.id===id?{...message,liked:true}:message))}};
 const openMessageManager=(message:GuestbookMessage)=>{setManageMessage(message);setManageName(message.nickname);setManageText(message.content);setManageKey('');setManageError('');setDeleteArmed(false)};
 const closeMessageManager=()=>{setManageMessage(null);setManageKey('');setManageError('');setDeleteArmed(false)};
 const saveManagedMessage=async()=>{if(!manageMessage)return;setManageSaving(true);setManageError('');try{const updatedAt=await updateGuestbookMessage(manageKey,manageMessage.id,manageName,manageText);setMessages(current=>current.map(message=>message.id===manageMessage.id?{...message,nickname:manageName.trim(),content:manageText.trim(),updatedAt}:message));closeMessageManager()}catch(e){setManageError(e instanceof Error?e.message:'修改失败，请重试')}finally{setManageSaving(false)}};
 const removeManagedMessage=async()=>{if(!manageMessage)return;if(!deleteArmed){setDeleteArmed(true);return}setManageSaving(true);setManageError('');try{await deleteGuestbookMessage(manageKey,manageMessage.id);setMessages(current=>current.filter(message=>message.id!==manageMessage.id));closeMessageManager()}catch(e){setManageError(e instanceof Error?e.message:'删除失败，请重试')}finally{setManageSaving(false)}};
 const openComments=async(message:GuestbookMessage)=>{setCommentMessage(message);setComments([]);setCommentText('');setCommentPosted(message.commented);setCommentError('');setCommentLoading(true);try{setComments(await listGuestbookComments(message.id))}catch{setCommentError('评论暂时未能加载，请稍后重试。')}finally{setCommentLoading(false)}};
 const closeComments=()=>{setCommentMessage(null);setComments([]);setCommentText('');setCommentError('');setDeleteComment(null);setCommentDeleteKey('');setCommentDeleteError('')};
 const submitComment=async()=>{if(!commentMessage)return;setCommentSaving(true);setCommentError('');try{const added=await postGuestbookComment(commentMessage.id,commentName,commentText);setComments(current=>[...current,added]);setMessages(current=>current.map(message=>message.id===commentMessage.id?{...message,comments:message.comments+1,commented:true}:message));setCommentMessage(current=>current?{...current,comments:current.comments+1,commented:true}:current);setCommentPosted(true);setCommentText('')}catch(e){const text=e instanceof Error?e.message:'评论失败，请重试';setCommentError(text);if(text.includes('已经评论过'))setCommentPosted(true)}finally{setCommentSaving(false)}};
 const removeComment=async()=>{if(!deleteComment||!commentMessage)return;setCommentDeleting(true);setCommentDeleteError('');try{await deleteGuestbookComment(commentDeleteKey,deleteComment.id);setComments(current=>current.filter(comment=>comment.id!==deleteComment.id));setMessages(current=>current.map(message=>message.id===commentMessage.id?{...message,comments:Math.max(0,message.comments-1)}:message));setCommentMessage(current=>current?{...current,comments:Math.max(0,current.comments-1)}:current);setDeleteComment(null);setCommentDeleteKey('')}catch(e){setCommentDeleteError(e instanceof Error?e.message:'删除评论失败，请重试')}finally{setCommentDeleting(false)}};
 const albumNames=[PUBLIC_ALBUM,...Array.from(new Set(photos.map(photo=>photo.album).filter((name):name is string=>Boolean(name)&&name!==PUBLIC_ALBUM)))];
 const visiblePhotos=activeAlbum===ALL_ALBUMS?photos:photos.filter(photo=>(photo.album??PUBLIC_ALBUM)===activeAlbum);
 const albumGroups=albumNames.map(name=>({name,photos:photos.filter(photo=>(photo.album??PUBLIC_ALBUM)===name)}));
 return <main>
 <header className="nav"><a className="brand" href="#home" aria-label="冒险岛怀旧服童话村首页"><Logo/>童话村</a><span className="nav-sub">冒险岛怀旧服</span><nav className="desktop-nav"><a href="#honors">荣誉馆</a><a href="#album">相册</a><a href="#guestbook">留言板</a><a href="#events">大事记</a><a href="#sponsors">贡献榜</a><button onClick={()=>setUpload(true)}>上传照片 <Plus size={17}/></button></nav><Music/><button className="mobile-menu" aria-label={menu?'关闭菜单':'打开菜单'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 {menu&&<nav className="mobile-overlay"><a href="#honors" onClick={()=>setMenu(false)}>百级荣誉馆 ↗</a><a href="#album" onClick={()=>setMenu(false)}>我们的相册 ↗</a><a href="#guestbook" onClick={()=>setMenu(false)}>村口留言板 ↗</a><a href="#events" onClick={()=>setMenu(false)}>童话村大事记 ↗</a><a href="#sponsors" onClick={()=>setMenu(false)}>家族贡献榜 ↗</a><button onClick={()=>{setMenu(false);setUpload(true)}}>上传照片 ＋</button></nav>}
 <section id="home" className="hero">
 <div className="hero-atmosphere" aria-hidden="true"><img className="hero-cloud hero-cloud-one" src={asset('hero-clouds.png')} alt=""/><img className="hero-cloud hero-cloud-two" src={asset('hero-clouds.png')} alt=""/><img className="hero-float hero-float-one" src={asset('clover.png')} alt=""/><img className="hero-float hero-float-two" src={asset('clover.png')} alt=""/><img className="hero-float hero-float-three" src={asset('clover.png')} alt=""/></div>
 <img className="hero-grass" src={asset('hero-grass.png')} alt="" aria-hidden="true"/>
 <div className="hero-media"><canvas ref={canvas} width={800} height={450} className={framesReady?'frame-canvas ready':'frame-canvas'} aria-label="随鼠标位置左右转头的蘑菇" role="img"/></div>
 <div className="hero-copy"><h1><Logo/>童话村<span className="title-dot">.</span></h1><div className="hero-actions"><a className="pill primary" href="#album">翻开我们的回忆 <ArrowUpRight size={18}/></a><button className="pill" onClick={()=>setUpload(true)}>留下一张照片 <Plus size={17}/></button></div></div>
 <div className="hero-bottom"><a href="#honors" className="scroll-link"><ArrowDown size={17}/> 往下，走进百级荣誉馆</a><span className="mouse-hint"><MoveHorizontal size={20}/> 左右移动鼠标，和蘑菇打个招呼</span><span className="page-index">01 — 06</span></div>
 </section>
 <section id="honors" className="honors section"><div className="eyebrow">LEVEL 100 · HALL OF HONOR</div><h2>百级荣誉馆<span className="section-dot">.</span></h2><p className="section-description">童话村率先抵达100级的冒险家</p><div className="honor-grid">{honors.map(person=><article className="honor-card" key={person.name}><div className="honor-stage"><span className="level-badge">LV.100</span><img src={asset(person.image)} alt={`${person.name}，${person.job}`} loading="lazy"/><span className="honor-shadow"/></div><div className="honor-copy"><div><h3>{person.name}</h3><p>{person.job}</p></div><time dateTime={person.date.replaceAll('.','-')}>{person.date}<small>达到100级</small></time></div></article>)}</div></section>
 <section id="album" className="album"><div className="album-heading"><div><div className="eyebrow">OUR MEMORIES / 相册</div><h2>一起走过的冒险<span>（{String(photos.length).padStart(2,'0')}）</span></h2></div><button className="pill" onClick={()=>{setAlbumName(activeAlbum===ALL_ALBUMS?PUBLIC_ALBUM:activeAlbum);setUpload(true)}}>上传照片 <Plus size={18}/></button></div><p className="album-note">有你在的地方，就是童话村。</p>{albumError&&<p role="status" className="error">{albumError}</p>}{activeAlbum===ALL_ALBUMS?<><div className="album-category-heading"><strong>相册分类</strong><span>点击一本相册，翻看里面的全部回忆</span></div><div className="album-overview">{albumGroups.map(({name,photos:group})=><button className="album-card" key={name} onClick={()=>setActiveAlbum(name)}><div className="album-cover">{(covers[name]||group[0]?.src)?<img src={covers[name]||group[0].src} alt="" loading="lazy"/>:<span>还没有照片</span>}{name==='小兔Daily'&&<BunnyMascot/>}{name==='小青蛙的旅行日记'&&<LycheeMascot/>}{name==='小船长个人秀'&&<BoatMascot/>}{name==='喜羊羊的征婚相册'&&<SheepMascot/>}<div className="album-stack"/><b>{group.length} 张</b></div><div className="album-card-copy"><div><h3>{name}</h3><p>{name===PUBLIC_ALBUM?'童话村的共同回忆':'个人相册专区'}</p></div><ArrowUpRight size={20}/></div></button>)}</div></>:<><div className="album-inside-heading"><button onClick={()=>setActiveAlbum(ALL_ALBUMS)}><ArrowLeft size={17}/> 返回全部相册</button><div className="album-tools"><div className="album-action-row"><button className="album-action" onClick={()=>setCoverAlbum(activeAlbum)}><ImageIcon size={16}/> 设置封面</button>{activeAlbum!==PUBLIC_ALBUM&&<button className="album-action" onClick={()=>{setRenameTarget(activeAlbum);setNewAlbumName(activeAlbum)}}><Pencil size={15}/> 修改名称</button>}</div><div><strong>{activeAlbum}</strong><span>{visiblePhotos.length} 张照片</span></div></div></div><div className={visiblePhotos.length===1?"photo-grid single-photo":"photo-grid"}>{visiblePhotos.map((p,i)=><button className="photo-card" key={p.src} onClick={()=>setActive(photos.indexOf(p))}><div className="photo-image"><img src={p.src} alt={p.name} loading="lazy"/><span className="photo-open"><ArrowUpRight size={22}/></span></div><div className="photo-caption"><div><h3>{p.name}</h3><p>{p.album??PUBLIC_ALBUM}</p></div><span>{String(i+1).padStart(2,'0')}</span></div></button>)}</div>{visiblePhotos.length===0&&<div className="album-empty">这个相册还没有照片。</div>}</>}</section>
 <section id="guestbook" className="guestbook section"><div className="eyebrow">VILLAGE VOICES / 村民留下的话</div><h2>村口留言板<span className="section-dot">.</span></h2><p className="section-description">一句问候，一段回忆，都留在村口的木牌上。高赞留言会排在前面。</p><div className="guestbook-layout"><div className="guestbook-compose">{messagePosted?<div className="message-thanks"><Check size={25}/><strong>你已经留下过留言</strong><p>每台设备只能写一次，但你仍然可以为喜欢的留言点赞。</p></div>:<><label>你的游戏昵称<input maxLength={20} value={messageName} onChange={e=>setMessageName(e.target.value)} placeholder="例如：小蓝天丶" disabled={messageSaving}/></label><label>想说的话<textarea maxLength={160} rows={5} value={messageText} onChange={e=>setMessageText(e.target.value)} placeholder="写下想留给童话村的一句话……" disabled={messageSaving}/><span>{messageText.length} / 160</span></label><button className="message-submit" disabled={messageSaving||!messageName.trim()||!messageText.trim()} onClick={submitMessage}>{messageSaving?'正在留下留言…':'把留言挂上去'}<Send size={17}/></button><small>同一设备仅可提交一次留言</small></>}{messageError&&<p role="alert" className="error">{messageError}</p>}</div><div className="message-wall" aria-live="polite">{messageLoading?<div className="message-empty">正在打开留言板…</div>:messages.length===0?<div className="message-empty">还没有留言，来写下第一句话吧。</div>:messages.map(message=><article className="message-card" key={message.id}><div className="message-meta"><strong>{message.nickname}</strong><time dateTime={message.createdAt}>{messageTime(message.createdAt)}{message.updatedAt&&<small> · 已编辑</small>}</time></div><p>{message.content}</p><button className={message.liked?'like-button liked':'like-button'} disabled={message.liked} onClick={()=>likeMessage(message.id)} aria-label={message.liked?'已点赞':`给${message.nickname}的留言点赞`}><Heart size={17} fill={message.liked?'currentColor':'none'}/><span>{message.likes}</span></button><button className="comment-button" onClick={()=>openComments(message)} aria-label={`查看${message.nickname}留言的评论`}><MessageCircle size={15}/><span>{message.comments}</span></button><button className="message-manage" onClick={()=>openMessageManager(message)}><Pencil size={14}/> 管理</button></article>)}</div></div></section>
 <section id="events" className="events section"><div className="eyebrow">OUR STORY / 大事记</div><h2>童话村大事记<span className="section-dot">.</span></h2><div className="timeline"><div className="year">2026<span>故事的开始</span></div><div className="event-list">{events.map(([date,title,location])=><article className="event" key={date}><time dateTime={'2026-'+date.replace('.','-')}>{date}</time><div><h3>{title}</h3><p>{location}</p></div></article>)}</div></div></section>
 <section id="sponsors" className="sponsors section"><div className="eyebrow">WITH THANKS / 感谢每一份支持</div><h2>家族贡献榜<span className="section-dot">.</span></h2><p className="section-description">童话村赞助商名单 · 后续赞助将持续记录于此</p><div className="sponsor-groups">{[['游戏币赞助',sponsors.slice(0,15)],['人民币赞助',sponsors.slice(15)]].map(([label,list])=><div className="sponsor-group" key={label as string}><h3>{label as string}<span>{label==='游戏币赞助'?'W = 万游戏币':'RMB = 人民币'}</span></h3><div className="sponsor-list">{(list as string[][]).map(([name,amount])=><div className="sponsor-row" key={name}><span>{name}</span><strong>{amount}</strong></div>)}</div></div>)}</div></section>
 <footer><a className="brand" href="#home"><Logo/>童话村</a><span>冒险的故事，未完待续。</span><a href="#home">回到顶部 ↑</a></footer>
 <Dialog open={upload} onOpenChange={setUpload}><DialogContent className="upload-dialog"><DialogTitle className="dialog-title">留下一张回忆</DialogTitle><DialogDescription>选择已有相册，或直接输入新名字创建个人相册。</DialogDescription><label className="upload-key-label">上传口令<input type="password" autoComplete="current-password" value={uploadKey} onChange={e=>setUploadKey(e.target.value)} placeholder="仅你本人知道" disabled={saving}/></label><label className="upload-key-label">相册名称<input list="album-name-options" maxLength={40} value={albumName} onChange={e=>setAlbumName(e.target.value)} placeholder="例如：小明的相册" disabled={saving}/><datalist id="album-name-options">{albumNames.map(name=><option value={name} key={name}/>)}</datalist></label><label className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files)}}><Upload size={30}/><strong>{compressing?'正在优化照片…':'点击选择，或拖入照片'}</strong><span>{compressing?'大图正在自动压缩，请稍候':'JPG / PNG / WebP / GIF · 每张不超过 20 MB'}</span><input type="file" disabled={saving||compressing} multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>{choose(e.target.files);e.target.value=''}}/></label>{error&&<p role="alert" className="error">{error}</p>}{pending.length>0&&<div className="pending-grid">{pending.map((p,i)=><div key={p.src}><img src={p.src} alt={p.name}/><button aria-label={'移除 '+p.name} disabled={saving} onClick={()=>setPending(s=>s.filter((_,j)=>i!==j))}><X size={14}/></button><input aria-label={`第${i+1}张照片名称`} maxLength={80} value={p.name} disabled={saving} placeholder="照片名称" onChange={e=>setPending(s=>s.map((item,j)=>j===i?{...item,name:e.target.value}:item))}/></div>)}</div>}<button className="pill primary add-button" disabled={saving||compressing||!pending.length||!uploadKey||!albumName.trim()} onClick={savePhotos}>{saving?'正在上传…':compressing?'正在优化…':`上传并保存${pending.length?`（${pending.length}）`:''}`}<ArrowUpRight size={18}/></button></DialogContent></Dialog>
 <Dialog open={active!==null} onOpenChange={o=>{if(!o)setActive(null)}}><DialogContent className="lightbox">{active!==null&&<><DialogTitle>{photos[active].name}</DialogTitle><PhotoViewer key={photos[active].src} src={photos[active].src} name={photos[active].name}/><div className="lightbox-bottom"><DialogDescription>{photos[active].note} · {active+1} / {photos.length}</DialogDescription><div>{photos[active].path&&<button className="delete-photo" aria-label="删除照片" title="删除照片" onClick={()=>{setDeleteTarget(photos[active]);setActive(null)}}><Trash2 size={18}/></button>}<button aria-label="上一张" onClick={()=>setActive((active+photos.length-1)%photos.length)}><ArrowLeft/></button><button aria-label="下一张" onClick={()=>setActive((active+1)%photos.length)}><ArrowRight/></button></div></div></>}</DialogContent></Dialog>
 <Dialog open={deleteTarget!==null} onOpenChange={o=>{if(!o&&!deleting){setDeleteTarget(null);setDeleteKey('');setDeleteError('')}}}><DialogContent className="delete-dialog"><DialogTitle className="dialog-title">删除这张照片？</DialogTitle><DialogDescription>“{deleteTarget?.name}”将从公开相册中永久删除。请输入管理员上传口令确认。</DialogDescription><label className="upload-key-label">上传口令<input type="password" autoComplete="current-password" value={deleteKey} onChange={e=>setDeleteKey(e.target.value)} disabled={deleting}/></label>{deleteError&&<p role="alert" className="error">{deleteError}</p>}<button className="delete-confirm" disabled={!deleteKey||deleting} onClick={confirmDelete}>{deleting?'正在删除…':'确认删除'}</button></DialogContent></Dialog>
 <Dialog open={coverAlbum!==null} onOpenChange={o=>{if(!o&&!coverSaving)closeCover()}}><DialogContent className="cover-dialog"><DialogTitle className="dialog-title">设置“{coverAlbum}”的封面</DialogTitle><DialogDescription>从已上传的照片中选择，或者单独上传一张封面图。</DialogDescription>{visiblePhotos.length>0&&<><div className="cover-label">选择相册内的照片</div><div className="cover-picker">{visiblePhotos.map(photo=><button className={coverPhoto===photo?'cover-option selected':'cover-option'} key={photo.src} onClick={()=>{chooseCoverFile(null);setCoverPhoto(photo)}}><img src={photo.src} alt={photo.name}/>{coverPhoto===photo&&<span><Check size={17}/></span>}</button>)}</div></>}<label className="cover-upload"><ImageIcon size={21}/><span>{coverFile?coverFile.name:'单独上传封面照片'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={coverSaving} onChange={e=>{chooseCoverFile(e.target.files?.[0]??null);e.target.value=''}}/></label>{coverPreview&&<img className="cover-preview" src={coverPreview} alt="待上传的相册封面"/>}<label className="upload-key-label">上传口令<input type="password" autoComplete="current-password" value={coverKey} onChange={e=>setCoverKey(e.target.value)} disabled={coverSaving}/></label>{coverError&&<p role="alert" className="error">{coverError}</p>}<button className="pill primary add-button" disabled={coverSaving||!coverKey||(!coverPhoto&&!coverFile)} onClick={confirmCover}>{coverSaving?'正在设置…':'保存相册封面'}<ArrowUpRight size={18}/></button></DialogContent></Dialog>
 <Dialog open={renameTarget!==null} onOpenChange={o=>{if(!o&&!renaming)closeRename()}}><DialogContent className="rename-dialog"><DialogTitle className="dialog-title">修改相册名称</DialogTitle><DialogDescription>相册内的照片和已经设置的封面都会保留。</DialogDescription><label className="upload-key-label">新的相册名称<input maxLength={40} value={newAlbumName} onChange={e=>setNewAlbumName(e.target.value)} disabled={renaming}/></label><label className="upload-key-label">上传口令<input type="password" autoComplete="current-password" value={renameKey} onChange={e=>setRenameKey(e.target.value)} disabled={renaming}/></label>{renameError&&<p role="alert" className="error">{renameError}</p>}<button className="pill primary add-button" disabled={renaming||!renameKey||!newAlbumName.trim()||newAlbumName.trim()===renameTarget} onClick={confirmRename}>{renaming?'正在修改…':'保存新名称'}<ArrowUpRight size={18}/></button></DialogContent></Dialog>
 <Dialog open={commentMessage!==null} onOpenChange={o=>{if(!o&&!commentSaving&&!commentDeleting)closeComments()}}><DialogContent className="comments-dialog"><DialogTitle className="dialog-title">{commentMessage?.nickname} 的留言</DialogTitle><DialogDescription className="comment-original">{commentMessage?.content}</DialogDescription><div className="comment-list" aria-live="polite">{commentLoading?<p>正在打开评论…</p>:comments.length===0?<p>还没有评论，来留下第一句回应吧。</p>:comments.map(comment=><article key={comment.id}><div><strong>{comment.nickname}</strong><span><time dateTime={comment.createdAt}>{messageTime(comment.createdAt)}</time><button aria-label={`删除${comment.nickname}的评论`} onClick={()=>{setDeleteComment(comment);setCommentDeleteKey('');setCommentDeleteError('')}}><Trash2 size={13}/></button></span></div><p>{comment.content}</p></article>)}</div>{deleteComment&&<div className="comment-delete-panel"><span>删除“{deleteComment.nickname}”的评论</span><label>上传口令<input type="password" autoComplete="current-password" value={commentDeleteKey} onChange={e=>setCommentDeleteKey(e.target.value)} disabled={commentDeleting}/></label>{commentDeleteError&&<p role="alert" className="error">{commentDeleteError}</p>}<div><button onClick={()=>{setDeleteComment(null);setCommentDeleteKey('');setCommentDeleteError('')}} disabled={commentDeleting}>取消</button><button onClick={removeComment} disabled={commentDeleting||!commentDeleteKey}>{commentDeleting?'正在删除…':'确认删除'}</button></div></div>}{commentPosted?<div className="comment-thanks"><Check size={19}/><span>你已经评论过这条留言</span></div>:<div className="comment-compose"><label>你的游戏昵称<input maxLength={20} value={commentName} onChange={e=>setCommentName(e.target.value)} placeholder="例如：小蓝天丶" disabled={commentSaving}/></label><label>回复内容<textarea maxLength={160} rows={3} value={commentText} onChange={e=>setCommentText(e.target.value)} placeholder="写下一句回应……" disabled={commentSaving}/><span>{commentText.length} / 160</span></label><button disabled={commentSaving||!commentName.trim()||!commentText.trim()} onClick={submitComment}>{commentSaving?'正在评论…':'发表评论'}<Send size={16}/></button><small>每台设备对这条留言仅可评论一次</small></div>}{commentError&&<p role="alert" className="error">{commentError}</p>}</DialogContent></Dialog>
 <Dialog open={manageMessage!==null} onOpenChange={o=>{if(!o&&!manageSaving)closeMessageManager()}}><DialogContent className="message-manage-dialog"><DialogTitle className="dialog-title">管理留言</DialogTitle><DialogDescription>使用管理员上传口令修改或删除这条留言。</DialogDescription><label className="upload-key-label">游戏昵称<input maxLength={20} value={manageName} onChange={e=>setManageName(e.target.value)} disabled={manageSaving}/></label><label className="upload-key-label">留言内容<textarea maxLength={160} rows={5} value={manageText} onChange={e=>setManageText(e.target.value)} disabled={manageSaving}/><span className="manage-count">{manageText.length} / 160</span></label><label className="upload-key-label">上传口令<input type="password" autoComplete="current-password" value={manageKey} onChange={e=>{setManageKey(e.target.value);setDeleteArmed(false)}} disabled={manageSaving}/></label>{manageError&&<p role="alert" className="error">{manageError}</p>}<div className="manage-actions"><button className={deleteArmed?'manage-delete armed':'manage-delete'} disabled={manageSaving||!manageKey} onClick={removeManagedMessage}><Trash2 size={16}/>{deleteArmed?'再次点击确认删除':'删除留言'}</button><button className="manage-save" disabled={manageSaving||!manageKey||!manageName.trim()||!manageText.trim()} onClick={saveManagedMessage}>{manageSaving?'正在处理…':'保存修改'}<ArrowUpRight size={17}/></button></div></DialogContent></Dialog>
 </main>
}
