'use client';
import {useEffect,useRef,useState} from 'react';
import {Music2,VolumeX,ZoomIn,ZoomOut,RotateCcw} from 'lucide-react';
import {transparentSurface} from './matte';
const asset=(path:string)=>new URL(path,document.baseURI).href;
export function Logo(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{let gone=false;const img=new Image();img.src=asset('clover.png');img.decode().then(()=>{if(gone||!ref.current)return;const c=transparentSurface(img);ref.current.width=c.width;ref.current.height=c.height;ref.current.getContext('2d')?.drawImage(c,0,0)}).catch(()=>{});return()=>{gone=true}},[]);return <canvas ref={ref} className="clover" role="img" aria-label="童话村四叶草标志"/>}
export function Music(){
 const ref=useRef<HTMLAudioElement>(null),choice=useRef(false);const [playing,setPlaying]=useState(false),[failed,setFailed]=useState(false);
 useEffect(()=>{const a=ref.current!;a.volume=.2;try{choice.current=localStorage.getItem('village-music')==='off'}catch{}
 const attempt=()=>{if(!choice.current)a.play().catch(()=>{})};const gesture=(e:Event)=>{if((e.target as Element)?.closest?.('.music-control'))return;attempt()};if(!choice.current)attempt();window.addEventListener('pointerdown',gesture);window.addEventListener('keydown',gesture);return()=>{window.removeEventListener('pointerdown',gesture);window.removeEventListener('keydown',gesture);a.pause()};},[]);
 const toggle=()=>{const a=ref.current!;if(!a.paused){choice.current=true;a.pause();try{localStorage.setItem('village-music','off')}catch{}}else{choice.current=false;setFailed(false);try{localStorage.setItem('village-music','on')}catch{}a.play().catch(()=>setFailed(true))}};
 return <div className="music-control"><audio ref={ref} loop preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>{setPlaying(false);setFailed(true)}}><source src={asset('temple-of-time.mp3')} type="audio/mpeg"/><source src={asset('temple-of-time.ogg')} type="audio/ogg"/></audio><button onClick={toggle} className={playing?'music-toggle playing':'music-toggle'} aria-pressed={playing} aria-label={playing?'暂停背景音乐':'播放背景音乐'} title={failed?'音乐暂时无法播放，点击重试':playing?'暂停《时间神殿》':'播放《时间神殿》'}>{playing?<Music2 size={18}/>:<VolumeX size={18}/>}<span>时间神殿</span></button>{failed&&<span className="music-error" role="status">点击重试</span>}</div>
}
export function PhotoViewer({src,name}:{src:string,name:string}){
 const viewport=useRef<HTMLDivElement>(null);
 const [view,setView]=useState({scale:1,x:0,y:0});const current=useRef(view);current.current=view;
 const pointers=useRef(new Map<number,{x:number,y:number}>());const previous=useRef<{x:number,y:number,d:number}|null>(null);
 const change=(scale:number,x:number,y:number)=>{scale=Math.max(1,Math.min(5,scale));const w=viewport.current?.clientWidth??0,h=viewport.current?.clientHeight??0;const bx=w*(scale-1)/2,by=h*(scale-1)/2;setView({scale,x:Math.max(-bx,Math.min(bx,x)),y:Math.max(-by,Math.min(by,y))})};
 useEffect(()=>{const el=viewport.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const v=current.current;change(v.scale*(e.deltaY>0?.9:1.1),v.x,v.y)};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[]);
 const metrics=()=>{const a=[...pointers.current.values()];if(!a.length)return null;return a.length===1?{...a[0],d:0}:{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2,d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}};
 return <><div ref={viewport} className={'photo-viewport'+(view.scale>1?' zoomed':'')} tabIndex={0} aria-label="照片查看器，使用加减按钮缩放，放大后拖动；方向键移动，0复位" onDoubleClick={()=>change(view.scale===1?2:1,0,0)} onKeyDown={e=>{const v=current.current;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='0')change(1,0,0);else if(e.key==='+'||e.key==='=')change(v.scale+.25,v.x,v.y);else if(e.key==='-')change(v.scale-.25,v.x,v.y);else change(v.scale,v.x+(e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0),v.y+(e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0));}}}
 onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});previous.current=metrics()}}
 onPointerMove={e=>{if(!pointers.current.has(e.pointerId))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const next=metrics(),prev=previous.current;if(next&&prev){const v=current.current;change(prev.d&&next.d?v.scale*next.d/prev.d:v.scale,v.x+next.x-prev.x,v.y+next.y-prev.y)}previous.current=next}}
 onPointerUp={e=>{pointers.current.delete(e.pointerId);previous.current=metrics()}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);previous.current=metrics()}}><img draggable={false} src={src} alt={name} style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.scale})`}}/></div><div className="zoom-toolbar"><span>滚轮缩放 · 拖动查看<span className="touch-tip"> / 双指缩放</span></span><div><button aria-label="缩小照片" disabled={view.scale===1} onClick={()=>change(view.scale-.5,view.x,view.y)}><ZoomOut size={18}/></button><output>{Math.round(view.scale*100)}%</output><button aria-label="放大照片" disabled={view.scale===5} onClick={()=>change(view.scale+.5,view.x,view.y)}><ZoomIn size={18}/></button><button aria-label="复位照片" onClick={()=>change(1,0,0)}><RotateCcw size={17}/></button></div></div></>
}
