create table if not exists public.guestbook_comments (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.guestbook_messages(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 20),
  content text not null check (char_length(content) between 1 and 160),
  device_hash text not null,
  created_at timestamptz not null default now(),
  unique (message_id, device_hash)
);

alter table public.guestbook_comments enable row level security;

create policy "Public reads guestbook comments" on public.guestbook_comments
  for select using (true);
create policy "Public comments once per message" on public.guestbook_comments
  for insert with check (true);

revoke select on public.guestbook_comments from anon, authenticated;
grant select (id, message_id, nickname, content, created_at) on public.guestbook_comments to anon, authenticated;
grant insert (message_id, nickname, content, device_hash) on public.guestbook_comments to anon, authenticated;
grant usage, select on sequence public.guestbook_comments_id_seq to anon, authenticated;
